### ISSUE TITLE
Moving repository / rename of rework-repository

### ISSUE THREAD

**Issue by aspdye** [owncloudarchive/contacts#1143]
I think we should:

- [x] Move this Repository to the "ownCloud Archive" organization.
- [x] Rename the "contactsrework"-repository to "contacts"

cc @DeepDiver1975 

Same will be done for calendar and calendar-rework soon: https://github.com/owncloud/calendar/issues/1037

**Comment by DeepDiver1975** [comment]
As discussed with @karlitschek - we will walk this path .... will execute this today ...
