### ISSUE TITLE
iOS/Mac OS X group compatibility.

### ISSUE THREAD

**Issue by ghost** [owncloudarchive/contacts#266]
Hi,

there is a issue with the standard contacts.app on Mac OS X and the CardDAV synchronisation. 

Groups are added by contacts.app as a contact with following attribute:
X-ADDRESSBOOKSERVER-KIND:group
And the contacts which are in the group are also written in the same contact as following:
X-ADDRESSBOOKSERVER-MEMBER:urn:uuid:742934923482348238423834

So my suggestion is, to create a workaround. My abilities are not good enough to do it myself. 

OwnCloud should have the option "Compatiblity with Mac OS X" => when this is activated then there should be automatically created cards with the X-ADDRESSBOOKSERVER-KIND:group attribute and linked with the cards and the real groups. So the synchronisation will be correct between Contacts.app and OwnCloud!

**Comment by appinteractive** [comment]
Any news on this issue?

**Comment by RandieM** [comment]
Hello there. 
Is anyone working on this may be?
It would be really great if the issue with the contact groups on Mac OS X could be solved. I understand that this is more because or Apple's unwillingness to stick to standards, but we have customers complaining to us that <i>our</i> product does not work.

**Comment by lofloflof** [comment]
Hi everyone!
I really love ownCloud and the recent development of everything. But like the other people here I'm really missing the group sync feature for OS X. As the past post is more than a year old … are there any news on that? 

Please? :)

**Comment by rgr101** [comment]
For some time, I'm using BusyCal and BusyContacts - ok, they are not for free, but fortunately, I grabbed a special offer... I have been sick of the non-standard OS X Group handling and no solution in sight... 

I'm planning to switch to Nextcloud anyway; hopefully they are trying harder on this topic ;-)

**Comment by DeepDiver1975** [comment]
FYI: the current development is within https://github.com/owncloud/contacts - I'm closing this issue in here
