### ISSUE TITLE
File selector in contacts import uses wrong file type filter

### ISSUE THREAD

**Issue by Pastafarianist** [owncloudarchive/contacts#771]
I am using ownCloud v7.0.3.

In "contacts" app, there is an option to select the format of import. After choosing "Gmail CSV" and opening the file selector, the file filter is set up to allow only for vCard files, not CSV.

**Comment by jbtbnl** [comment]
@Pastafarianist have you tested this against the development branch? The import dialog has been redesigned, and possibly fixes your issue.

**Comment by babelouest** [comment]
He has a point, in the stable branch, there is still only vcard files as input filter: https://github.com/owncloud/contacts/blob/stable7/templates/contacts.php#L54
=> https://github.com/owncloud/contacts/pull/776
The master branch is clean though

**Comment by babelouest** [comment]
Is the problem still there ? A related PR has been merged a few months ago #795

**Comment by Pastafarianist** [comment]
In ownCloud 8.2.2 the filter is disabled entirely.
